! DESCRIP.MMS - build PCRE2 (8-bit, Unicode, no JIT) for OpenVMS IA64 / x86-64
!
! Run via [.VMS]BUILD.COM, which passes ARCH and creates the output
! directories.  Source lists and per-object rules come from [.VMS]SOURCES.MMS,
! generated by tools/prepare.sh on the host.
!
! Outputs:
!   [.OBJ_<arch>]PCRE2-8.OLB          the library
!   [.BIN_<arch>]PCRE2TEST.EXE        the test program
!   [.INSTALL_<arch>.INCLUDE]PCRE2.H  install tree used by other ports (grep)
!   [.INSTALL_<arch>.LIB]PCRE2-8.OLB

.IFDEF ARCH
.ELSE
ARCH = IA64
.ENDIF

OBJ = [.OBJ_$(ARCH)]
LOBJ = [.OBJ_$(ARCH).LIB]
BIN = [.BIN_$(ARCH)]
INST = [.INSTALL_$(ARCH)

.INCLUDE [.VMS]SOURCES.MMS

CC = CC
CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./src")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H,PCRE2_CODE_UNIT_WIDTH=8)

LIB = $(OBJ)PCRE2-8.OLB

ALL : $(LIB), $(BIN)PCRE2TEST.EXE, $(INST).LIB]PCRE2-8.OLB, $(INST).INCLUDE]PCRE2.H
	@ CONTINUE

$(LIB) : $(LIB_OBJS)
	IF F$SEARCH("$(MMS$TARGET)") .EQS. "" THEN LIBRARY/CREATE/OBJECT $(MMS$TARGET)
	LIBRARY/REPLACE/OBJECT $(MMS$TARGET) $(LOBJ)*.OBJ

$(BIN)PCRE2TEST.EXE : $(TEST_OBJS), $(LIB)
	LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)PCRE2TEST.MAP $(TEST_OBJS), $(LIB)/LIBRARY

$(INST).LIB]PCRE2-8.OLB : $(LIB)
	COPY $(MMS$SOURCE) $(MMS$TARGET)

$(INST).INCLUDE]PCRE2.H : [.SRC]PCRE2.H
	COPY $(MMS$SOURCE) $(MMS$TARGET)

CLEAN :
	IF F$SEARCH("$(LOBJ)*.*") .NES. "" THEN DELETE/NOLOG $(LOBJ)*.*;*
	IF F$SEARCH("$(OBJ)*.OBJ") .NES. "" THEN DELETE/NOLOG $(OBJ)*.OBJ;*,*.OLB;*,*.MAP;*
	IF F$SEARCH("$(BIN)*.*") .NES. "" THEN DELETE/NOLOG $(BIN)*.*;*
