#!/usr/bin/env python3
"""Apply overlay/vms/config/config-vms.txt to PCRE2's src/config.h.generic.

Usage: gen_config.py <config.h.generic> <config-vms.txt> > config.h

Fails if a listed name does not appear in the generic file, so that a new
PCRE2 release which renames or drops a setting is noticed.
"""
import re
import sys


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    text = open(sys.argv[1]).read()
    for n, line in enumerate(open(sys.argv[2]), 1):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        words = line.split(None, 2)
        op, name = words[0], words[1]
        value = words[2] if len(words) > 2 else '1'
        undef = re.compile(r'^/\* #undef %s \*/$' % re.escape(name), re.M)
        define = re.compile(r'^#define %s( .*)?$' % re.escape(name), re.M)
        if not (undef.search(text) or define.search(text)):
            sys.exit('gen_config.py: %s line %d: %s is not in %s'
                     % (sys.argv[2], n, name, sys.argv[1]))
        if op == 'define':
            new = '#define %s %s' % (name, value)
            text = undef.sub(new, text)
            text = define.sub(new, text)
        elif op == 'undef':
            new = '/* #undef %s */' % name
            text = define.sub(new, text)
        else:
            sys.exit('gen_config.py: line %d: unknown operation %r' % (n, op))
    sys.stdout.write('/* Generated by tools/gen_config.py for OpenVMS - do not edit. */\n')
    sys.stdout.write(text)


if __name__ == '__main__':
    main()
