#!/usr/bin/env python3
"""Write vms/sources.mms for PCRE2: object lists and one MMS rule per object.

Usage: gen_mms.py <CMakeLists.txt> <ccflags.txt> [clangflags.txt] > sources.mms

The library sources are PCRE2_SOURCES from upstream's CMakeLists.txt, so a
new release's additions are picked up automatically.  Library objects go to
$(LOBJ) (so the librarian can take them by wildcard), the POSIX wrapper to
$(POBJ), pcre2test to $(OBJ).
VSI C accepts a single /DEFINE, so the defines from ccflags.txt are split
out into CC_DEFS for descrip.mms to merge with its own.  The rules name the
object with $(CC_OBJECT), so that one list serves VSI C (/OBJECT=) and the
clang build (-c -o; flags from clangflags.txt as CLANG_FLAGS).
"""
import os
import re
import sys


def pcre2_sources(cmake):
    m = re.search(r'set\(\s*PCRE2_SOURCES\s+(.*?)\)', cmake, re.S)
    if not m:
        sys.exit('gen_mms.py: PCRE2_SOURCES not found in CMakeLists.txt')
    files = []
    for tok in m.group(1).split():
        tok = tok.replace('${PROJECT_BINARY_DIR}/', '').replace('${PROJECT_SOURCE_DIR}/', '')
        if tok.endswith('.c'):
            files.append(tok)
    return files


def rule(obj, path, flags='$(LIB_CFLAGS)'):
    d, f = os.path.split(path)
    vdir = '[.' + '.'.join(p.upper() for p in d.split('/')) + ']' if d else '[]'
    # Also depend on config.h and pcre2.h: MMS here tracks no header
    # dependencies, and a configuration change must rebuild everything.
    return ['%s : %s%s, [.SRC]config.h, [.SRC]pcre2.h' % (obj, vdir, f),
            '\t$(CC) %s $(CC_OBJECT)$(MMS$TARGET) $(MMS$SOURCE)' % flags, '']


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    lib = pcre2_sources(open(sys.argv[1]).read())
    flags = open(sys.argv[2]).read().strip()
    m = re.search(r'/DEFINE=\(([^)]*)\)', flags, re.I)
    defs = m.group(1) if m else ''
    qual = re.sub(r'/DEFINE=\([^)]*\)', '', flags, flags=re.I)

    clang = open(sys.argv[3]).read().strip() if len(sys.argv) == 4 else ''
    out = ['! Generated by tools/gen_mms.py - do not edit', '',
           'CC_QUAL = ' + qual, 'CC_DEFS = ' + defs, 'CLANG_FLAGS = ' + clang, '']
    objs, rules = [], []
    for s in lib:
        obj = '$(LOBJ)%s.OBJ' % os.path.splitext(os.path.basename(s))[0]
        objs.append(obj)
        rules += rule(obj, s)
    out.append('LIB_OBJS = ' + ', -\n\t'.join(objs))
    out.append('')
    # The POSIX wrapper is a separate library, as upstream's libpcre2-posix.
    out.append('POSIX_OBJS = $(POBJ)pcre2posix.OBJ')
    out.append('')
    rules += rule('$(POBJ)pcre2posix.OBJ', 'src/pcre2posix.c')
    # pcre2test sets PCRE2_CODE_UNIT_WIDTH itself, so it gets the plain flags.
    out.append('TEST_OBJS = $(OBJ)pcre2test.OBJ')
    out.append('')
    rules += rule('$(OBJ)pcre2test.OBJ', 'src/pcre2test.c', '$(CFLAGS)')
    print('\n'.join(out + rules))


if __name__ == '__main__':
    main()
